### ISSUE TITLE
Extend a domain model with ObjectStorage

### ISSUE THREAD

**Issue by pixelmatseriks** [evoWeb/extender#24]
Hi,
We found this extension and really like the idea to be able to extend classes this way.

When we tried to extend a domain model with a variable of type ObjectStorage we couldn't get it to work, if we changed the variable to e.g. string everything works fine.

Have you extend any domain model with an ObjectStorage variable?
If you have, do you have an example so we can see how it should be done?

Thanks

**Comment by garbast** [comment]
You need to add a $this->yourProperty = new ObjectStorage(); in the __construct
