### ISSUE TITLE
Return value of command must be an integer

### ISSUE THREAD

**Issue by georgringer** [evoWeb/extender#25]
The execute method of the command must return 0

![image](https://user-images.githubusercontent.com/1905663/111439368-976cac80-8705-11eb-97db-f06d8363d1ef.png)

**Comment by georgringer** [comment]
thx @garbast

**Comment by christophlehmann** [comment]
Can you backport it for 10.4?

**Comment by garbast** [comment]
It was quite some work but a new release with this fix for 10.4 is released.

**Comment by christophlehmann** [comment]
:-) Thank you!
