### ISSUE TITLE
Extension key not always right

### ISSUE THREAD

**Issue by thommyhh** [evoWeb/extender#28]
The extension key is expected to be the second part of the namespace, except for `\TYPO3\CMS\` where is is expected to be the third.

I tried to extend a class from the blog extension which uses the namespace `\T3G\AgencyPack\Blog`, which leads to the extension key `agency_pack`, which is wrong. Works when I use `agency_pack` in my `ext_localconf.php`.

This is not a show stopper, but I'm wondering, if we actually need the extension key and if yes, if this could somehow be resolved.

**Comment by garbast** [comment]
As you already wrote, the extension key is expected to be the second part of the namespace. For deviations, that do not follow the conventions, there is no support.

The class loader depends on detecting the extension key. I see no solution, that takes the configured extension_key from composer.json as there is no api for that. 

Sorry, but either stick to the standard or extender is not able to find extending models.

As long as we do not find a way to configure the class loader like event listeners via Services.yaml i have no idea of an workaround.

**Comment by thommyhh** [comment]
Thanks for the quick reply. First of all, I stick to the standard, but the blog extension doesn't.

As far as I can see, the extension is only used for kind of grouping the extends and is not used for actually accessing anything from the extension. So it looks like, it's not too big of an issue.

Though, iIt could be helpful to mention this in the docs.
