### ISSUE TITLE
ClassParser return false position of function end

### ISSUE THREAD

**Issue by jurajsulek** [evoWeb/extender#29]
Problem are functions like 
public function __construct(array $fileReferenceData, $factory = null)
    {
        $this->propertiesOfFileReference = $fileReferenceData;
        if (!$fileReferenceData['uid_local']) {
            throw new \InvalidArgumentException('Incorrect reference to original file given for FileReference.', 1300098528);
        }
        $this->originalFile = $this->getFileObject((int)$fileReferenceData['uid_local'], $factory);
    }

which have also  { } in the body, because you don't use the depth's here. The code is just:
if ($inFunction) {
                            $classes[$classCount - 1]['functions'][$functionName]['end'] = $lastLine;
                                $inFunction = false;
                        }

so you save the ending after the first occurance of } Normaly it is no problem, but if it is in the constructor then in the cache file you have an open function without closing brackets. And on the position where the constructor originaly was is:

/**
     * Constructor for a file in use object. Should normally not be used
     * directly, use the corresponding factory methods instead.
     *
     * @param array $fileReferenceData
     * @param ResourceFactory $factory
     *
     * @throws \InvalidArgumentException
     * @throws Exception\FileDoesNotExistException
     */

        $this->originalFile = $this->getFileObject((int)$fileReferenceData['uid_local'], $factory);
    }

i have adapted the
case T_FUNCTION: 
and added also the depht there:
 case T_FUNCTION:
                                $state = self::STATE_FUNCTION_HEAD;
                                $classCount = count($classes);
                                if ($depth > 0 && $classCount) {
                                    $inFunction = true;
                                    $functionName = $token[1];
                                    $classes[$classCount - 1]['functions'][$token[1]] = [
                                        'modifiers' => $mod,
                                        'doc' => $doc,
                                        'start' => $token[2],
                                        'depth' => $depth
                                    ];
                                }
                                break;

and this is my case: '}'

case '}':
                        $depth--;
                        if ($inFunction) {
                            $classes[$classCount - 1]['functions'][$functionName]['end'] = $lastLine;
                            if($classes[$classCount - 1]['functions'][$functionName]['depth'] >= $depth) {
                                $inFunction = false;
                            }
                        }
                        break;

**Comment by garbast** [comment]
I understand the problem, but it is a very rare poblem that could be fixed by calling a function and throw the exception there.

In general i discourage to much logic in constructors.

**Comment by jurajsulek** [comment]
Yes i agree, but this is a model from Typo3 Core "\TYPO3\CMS\Core\Resource\FileReference" which we needet to extend. i'm sure they have more such constructors there.
