### ISSUE TITLE
Extented class not considered

### ISSUE THREAD

**Issue by fsuter** [evoWeb/extender#31]
I am using sf_register with extender, to add custom fields. This all worked well so far. Recently the following changes happened:

- I changed a couple of variable declarations and method signatures, because a non-mandatory field was causing issue with typing in getters/setters
- My hosting upgraded the database from MariaDB 10.3 to MariaDB 10.6
- I updated TYPO3 from 11.5.23 to 11.5.26

I don't know if any of this influenced what is happening now, but the problem is the following: the class extension seems to work well, because the "compiled" class exists in `var/cache/code/extender`. But I have errors in the frontend, complaining that my custom fields are not found in class `Evoweb\SfRegister\Domain\Model\FrontendUser`. So it seems like the "compiled" class is not loaded for some reason.

In my local installation, running DDEV with the same PHP version (8.0.28) and MariaDB 10.6, it works fine.

Do you have any hint about what the issue could be? Thanks in advance, I'm quite at a loss here.

**Comment by garbast** [comment]
Sorry to hear, that you experience a problem. Could you try to clear the cache with "Clear all caches", check if the file is regenerated and if the namespace and class are found in the generated file?

**Comment by fsuter** [comment]
Thanks for your quick answer. Surprisingly your suggestion solved the problem. I had cleared the cache several times, but either using `typo3 cache:flush` on the command-line or the "Flush all cache" from the Maintenance module. That seems to have made a difference. It's weird anyway, since it was working fine locally, so maybe it's something else entirely on that live server (it's the only web site I have with this hoster, so I can't compare).

But it's working, so thanks again and let's hope the weirdness does not repeat itself.

**Comment by thommyhh** [comment]
@garbast @fsuter I've a similar problem. But in my case, clearing the cache doesn't help. I tried debugging the problem, which is cumbersome on a remote server without XDebug. It looks to me, that the Autoloading of `extender` just doesn't get activated.

I will investigate i further. I've one of you has any ideas, they are welcome.

**Comment by garbast** [comment]
Sorry to say that, but you shouldnt debug this on a remote server. Empty out the var/cache/code/extender and afterwards hit the "Flush all caches". This should recreate the merged files. If that is not working, you need to check what spl autoloaders are registered and if there is a conflict.

**Comment by thommyhh** [comment]
@garbast The generation of the files is working. The funny thing is, that it only breaks on the first request - without caching of course. The following requests work fine. And it did not happen on my local development system, of course, otherwise it would be easy to debug.

I just tried your suggestion, but it did not help. I will investigate the autoloaders.

**Comment by georgringer** [comment]
maybe that helps - currently also being clueless.
if the cache is cleared in the install tool, all is fine but if the cache is cleared via toolbar, the problem keeps coming up. the difference I found is in the file `/var/cache/data/extbase/ClassSchemata_ff9a3dfd3fdebe8d7ce5b7a91ff13d72a7a76646` which misses the properties I add dynamically

**Comment by Apen** [comment]
@georgringer i have the same problem as you. Clear cache via "install tool" = no problem. Via the toolbar, my model is not loaded anymore... Have you find any fixe for that?

TYPO3 12.4.1 - extender last commit version

Important note = i have the same problem with news on last version. Maybe a problem with the proxy class system?
