### ISSUE TITLE
PHP 8.0/8.1 compatibility

### ISSUE THREAD

**Issue by netcoop** [evoWeb/extender#32]
On PHP 8.x Extender throws an Exception (or Warnings in log file, depending on debug settings):
PHP Warning: Undefined array key "name" in typo3conf/ext/extender/Classes/Utility/ClassParser.php line 177

Changing line 177 from
`$this->classes[$class['name']] = $class;`
to
`$this->classes[$class['name'] ?? null] = $class;`
makes it work identical to earlier PHP versions.

**Comment by garbast** [comment]
Cant say, that i like the idea.

What you are doing is, thet $this->classes[ with $class[name] or null ] with class. If you have two non existing $class names you write twice to $this->classes[null]. That's a bad idea.

In addition i cant think of a case where a class has no name. The name should be always present and set in line 120.

Having a look into https://www.php.net/manual/de/function.token-get-all.php it seems as if the class is not directly followed by the classname. It is clearly a problem by the class you are using.

**Comment by netcoop** [comment]
If I debug with a breakpoint on line 177 I get a couple of classes with a name, and then I get 1 without. The only key that one has is ['eol']. I have no idea why it's there, but on PHP7.4 this results in a null value for $class['name'], that's why I thought this is the easiest solution. I have no idea whether this is caused by extender or by my setup (someone else has introduced extender to this project, so I do not know all details). I can see that the ['eol'] key is added in line 113.
