### ISSUE TITLE
TYPO3 v12 - Extended class not working after "clear all caches"

### ISSUE THREAD

**Issue by Apen** [evoWeb/extender#37]
Hi, 

Sometimes, the extension doesn't map the datas on the extended model.
It has been explained in #31 and i have the following problem.

- if i clear cache in the install tools, everything is working fine. My model is extended and datas are mapped. 
- when i clear "all caches" in the toolbar, my model is not extended on the first frontend hit (maybe its an hint). File in "/var/cache/code/extender" is not created. And this is the basic model that is loaded.
- second frontend hit, my model is extended, the file is created, but the extends properties datas are not mapped. I only have the fields empty. 

I have TYPO3 12.4.11 with composer and extender last commit version.
As i mentoned in the #31, i have this bug also in "news" with his own mecanism. So maybe its more typo3 related than your extension.

Have you got any idea?

**Comment by Apen** [comment]
Could it be a side effect of : 

![image](https://github.com/evoWeb/extender/assets/1135104/a809406f-3ee8-4cb3-8ff2-22c8b7b450b6)

https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.4.x/Important-100925-UseDedicatedCacheForDatabaseSchemaInformation.html

EDIT : Yeah thats it, thats a side effect of a new version. In 12.4.1 everything is working fine after executing the same scenario. This bug happen since 12.4.5, 12.4.4=OK, 12.4.5=KO. But its not related to the upper changelog.

**Comment by Apen** [comment]
Last message of the investigation, i think this is the culprit commit : https://github.com/TYPO3/typo3/commit/35157fbafaf3d898f2c2ec1e8eeb3ca760cd69d5

I am in developpement context, last 12.4.11 version, when i comment this lines, everything is fine. I don't know if you could do something.

**Comment by garbast** [comment]
Thanks for your extended and successful research.

Only idea that comes to my mind is, clearing the cache.di every time when a proxy class gets generated by extender ClassCacheManager::build. But if this would cause other side effects, i cant predict.

The idea behind this is, if a cache gets generated before a merged class was written, a new cache entry needs to be generated, to have every property and method present to be analysed.

On the flipside, it's some what reassuring, that this problem only happens in Development context.

Still, it would be nice to fix this.

**Comment by garbast** [comment]
I added a hook that clears the classCache after the cache.di cache was cleared on development

Resolved with 4e2d629
