### ISSUE TITLE
Typo3 13.4 There is no extension able to load the configuration for "class"

### ISSUE THREAD

**Issue by TobiXT** [evoWeb/extender#41]
Hello my Backend Crashes when I try to loade my extension.
in then Log is this. 
` There is no extension able to load the configuration for "class" (in "vendor/rasani/aww2025/Configuration//Services.yaml"). Looked for namespace "class", found "none".`

My Service yaml: 
`services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

 rasani\aww2025:
 resource: '../Classes/*'

  rasani\aww2025\Classes\Extending\Domain\Model\Address:
    tags:
      - name: 'extender.extends'
class: firendsoftypo3\tt-address\Domain\Model\Address`

**Comment by garbast** [comment]
Your config is wrong.

The composer.json in your extension declares the namespace
   "autoload": {
        "psr-4": {
            "Rasani\\Aww2025\\": "Classes/"
        }
    },

The extension firendsoftypo3\tt-address declares the namespace
	"autoload": {
		"psr-4": {
			"FriendsOfTYPO3\\TtAddress\\": "Classes"
		}
	},

So you need to use Rasani\Aww2025 for your extending address model and FriendsOfTYPO3\TtAddress for the model you want to extend.
