### ISSUE TITLE
It's not possible to extend model with object storage property

### ISSUE THREAD

**Issue by tmotyl** [evoWeb/extender#8]
Adding an object property which is an object storage, requires to add a line to the class constructor like
```
    public function __construct()
    {
        $this->newProperty = new \TYPO3\CMS\Extbase\Persistence\ObjectStorage();
    }
```
This however will result in having duplicated __construct method in the cached file.
This results in the fatal error:
Fatal error: Cannot redeclare __construct() in ...

**Comment by garbast** [comment]
Did you test and experience this behaviour in develop branch? It you tested in master please test in develop again and give feedback. The unit tests does not support the report of an error.

If develop works for you, i can release a new version with develop merged into master.

**Comment by Mabahe** [comment]
Hey Tymek! Should work with c2aa6aeccf2033f09c72090a7587113c1ac85dd7 and the merged fix for #9

The related issue is #2

**Comment by garbast** [comment]
@tmotyl could you please checkout the develop branch and confirm that its working for you? Then i can release a new version.

**Comment by garbast** [comment]
Closed due to missing reply
